{{ range .Values.nodes }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ $.Values.cluster }}
  name: {{ .short }}-creds-eso
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-vault
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: provisioning/bmc
        metadataPolicy: None
  refreshInterval: 1h
  target:
    name: {{ .short }}-creds
---
{{ end }}